"""added index to time_taken column

Revision ID: 036372c0a7c7
Revises: 268932c5c2c8
Create Date: 2026-03-23 10:56:58.155083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036372c0a7c7'
down_revision = '268932c5c2c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_time_taken'), ['time_taken'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_time_taken'))

    # ### end Alembic commands ###
