"""empty message

Revision ID: 6ff13cfd42ea
Revises: 036372c0a7c7
Create Date: 2026-03-24 10:23:53.502071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff13cfd42ea'
down_revision = '036372c0a7c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Integer(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_type', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('day_taken', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_day_taken'), ['day_taken'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_quiz_type'), ['quiz_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_quiz_type'))
        batch_op.drop_index(batch_op.f('ix_user_day_taken'))
        batch_op.drop_column('day_taken')
        batch_op.drop_column('quiz_type')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
