"""Added questions

Revision ID: d3bbd4a21d5f
Revises: 7fec2ccab771
Create Date: 2026-03-19 13:56:41.737464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3bbd4a21d5f'
down_revision = '7fec2ccab771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=128), nullable=False),
    sa.Column('option1', sa.String(length=128), nullable=False),
    sa.Column('option2', sa.String(length=128), nullable=False),
    sa.Column('option3', sa.String(length=128), nullable=False),
    sa.Column('option4', sa.String(length=128), nullable=False),
    sa.Column('correct_option', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    # ### end Alembic commands ###
